name: thesis
channels:
- defaults
- pytorch
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - jupyter
  - matplotlib
  - seaborn
  - pytorch
  - torchvision
  - h5py
  - pip:
    - tqdm
    - torchcontrib
    - tensorflow <2.5
    - tensorflow_federated
