name: thesis
channels:
- defaults
- pytorch
dependencies:
  - python >=3.7,<3.9
  - pip=20.2.4
  - numpy
  - pandas=1.3.1
  - jupyter=1.0.0
  - matplotlib=3.4.3
  - seaborn=0.11.0
  - pytorch>=1.8.1
  - tensorflow <=2.5
  - torchvision>=0.11.3
  - scikit-learn
  - scipy
  - h5py
  - cudatoolkit=11
  - pip:
    - tqdm
    - torchcontrib
    - nbstripout
    - KDEpy
